    version: '3'
    services:
        web:
            build:
                context: .
                dockerfile: Dockerfile
                args:
                    buildno: 1
            ports:
                - "5000:5000"
            command: python ./index_redis.py
            volumes:
                - .:/app
        consumer:
            build:
                context: .
                dockerfile: Dockerfile
                args:
                    buildno: 1
            command: celery -A celery_app worker -l INFO --pool=prefork --concurrency=3 -E -n consumer1@wally.com #-Q pipeline_2  -f %n-%i.log
            #command: ["celery", "worker", "--app=celery_app", "--loglevel=INFO"]
            depends_on:
                - redis
            volumes:
                - .:/app

        redis:
            image: redis:latest
            container_name: redis_service
            expose:
                - 6379

        flower:
            image: mher/flower
            restart: always
            #command: celery flower
            environment:
              - CELERY_BROKER_URL=redis://redis:6379/0
              - FLOWER_PORT=5555
            ports:
              - 5555:5555
            expose:
              - 5555
            depends_on:
              - redis
              - consumer
